Favorite
olexandrd/goit-advancedjs-team-3 pull request #27
Opened 2024-07-04 17:28 UTC by VityukY

add fav

2024-07-04 19:13 UTC, kazamov requested changes

2024-07-04 19:13 UTC, kazamov commented on src/css/favorites.css
> +  .practice-list::-webkit-scrollbar {
You are missing customization for the Firefox. You need to use also 'scrollbar-color' (https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) and 'scrollbar-width' (https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width)

2024-07-04 19:13 UTC, kazamov commented on src/css/favorites.css
> +  background-color: #f4f4f4;
use var(--light)

2024-07-04 19:13 UTC, kazamov commented on src/js/favorites-temp.js
> +const data = [
Do not commit temp data, it is only for your local development. You just need to read data from localStorage when you load the page

2024-07-04 19:13 UTC, kazamov commented on src/js/favorites.js
> +const jsonData = JSON.stringify(data);
Remove steps where you save temp data

2024-07-04 19:13 UTC, kazamov commented on src/partials/favorite.html
Remove empty file and its reference

2024-07-04 19:13 UTC, kazamov commented on src/js/favorites.js
> +  console.log('logic run again');
Remove all logs

2024-07-04 19:13 UTC, kazamov commented on src/js/favorites.js
> +        const pageItem = document.createElement('li');
Ideally would be to reuse a pagination component

2024-07-04 19:30 UTC, VityukY commented on src/css/favorites.css
> +  background-color: #f4f4f4;
+

2024-07-04 19:31 UTC, VityukY commented on src/js/favorites-temp.js
> +const data = [
я юзаю темп дату тому що ви не сейвете нічого в сторадж 
іззадоволенням почекав би декілька днів поки все зробиться з локал стораджом і почав би дивитись до задач)

2024-07-04 19:33 UTC, VityukY commented on src/js/favorites.js
> +const jsonData = JSON.stringify(data);
не можу без тим часових даних,бо не працює кнопка зберігання фейворіт за працює все заміню, мені зараз потрібна вся логіка яка є для роботи

2024-07-04 19:34 UTC, VityukY commented on src/js/favorites.js
> +  console.log('logic run again');
+

2024-07-04 19:35 UTC, VityukY commented on src/js/favorites.js
> +        const pageItem = document.createElement('li');
не можу пагінацію реюзати
тут не пагінація з бекенда. тут треба наявні дані в  стораджі дістати і самому розробити пагінацію і логіку під неї)

2024-07-04 19:54 UTC, VityukY commented on src/css/favorites.css
> +  .practice-list::-webkit-scrollbar {
додав тепер все попливло потім займуст

2024-07-04 19:55 UTC, VityukY reviewed
пофіксив

2024-07-04 20:18 UTC, kazamov requested changes

2024-07-04 20:18 UTC, kazamov commented on src/js/favorites.js
> +        const pageItem = document.createElement('li');
той pagination компонент не залежить від бекенд компонента. Функція що його малює (src/js/renderPagination.js) приймає два параметри - загальну кількість сторінок і поточну сторінку. Окремо і обробник на подію клік, який дістає номер сторінки яку треба завантажити із події. 

```
function onPaginationClick(e) {
  const target = e.target;
  const paginationItem =
    target.closest('li.pagination-item:not(.active):not(.three-dots)') ??
    target.closest('li.pagination-arrow:not(.disabled)');

  if (!paginationItem) return;

  const page = Number(paginationItem.dataset.id);
  
 ... your logic comes here
}
```

2024-07-04 20:18 UTC, kazamov commented on src/partials/favorite.html
Remove empty file and its reference

2024-07-04 20:22 UTC, VityukY commented on src/partials/favorite.html
done

2024-07-04 21:58 UTC, VityukY commented
1. доадв карточки - реюзнути не вдалось, прийшлось забрати весь код і вставляти собі окремо
2. поп-ап при натискані на карточки start - не знаю як підклчюити 
3. пагінація воркає - але не знаю як стилі приєднати собі ті які є
4. квоут і користь 110 хвилин - паршалами передаєтсья, але має інші розміри від мейн сторінки - особливо на таблетці і дестк топі помітно
5. на десктопі проблема з хедером є - не рішив поки
6. не зробив ще пусту перевірку - щоб писало текст

2024-07-05 11:51 UTC, kazamov approved these changes

2024-07-05 13:40 UTC, Sysqwerty commented on src/js/favorites.js
> +import data from './favorites-temp';
Please remove

2024-07-05 13:40 UTC, Sysqwerty commented on src/js/favorites-temp.js
> +const data = [
Додавання впрпв в сторадж вже зроблене. Можна видалити цей фіайл і його використання в favorites.js

2024-07-05 13:48 UTC, merged